import type { Machine, CodeSession, CodeEvent, CodeCommand, WatchedProject } from '@/types/code-monitor';

export const mockMachines: Machine[] = [
  {
    id: 'machine-1',
    name: 'dev-macbook',
    hostname: 'kayamoran-mbp.local',
    os: 'darwin',
    status: 'online',
    lastHeartbeat: Date.now() - 5000,
    activeSessions: 1,
    cpuUsage: 34.2,
    memUsage: 62.8,
    registeredAt: Date.now() - 86400000 * 7,
    authToken: '',
    source: 'local',
  },
  {
    id: 'machine-2',
    name: 'staging-server',
    hostname: 'staging-01.internal.dev',
    os: 'linux',
    status: 'busy',
    lastHeartbeat: Date.now() - 3000,
    activeSessions: 3,
    cpuUsage: 78.5,
    memUsage: 84.1,
    registeredAt: Date.now() - 86400000 * 14,
    authToken: '',
  },
  {
    id: 'machine-3',
    name: 'ci-runner',
    hostname: 'gh-runner-042.ci.example.com',
    os: 'linux',
    status: 'offline',
    lastHeartbeat: Date.now() - 120000,
    activeSessions: 0,
    cpuUsage: 0,
    memUsage: 0,
    registeredAt: Date.now() - 86400000 * 3,
    authToken: '',
  },
];

export const mockCodeSessions: CodeSession[] = [
  {
    id: 'csess-1',
    machineId: 'machine-1',
    machineName: 'dev-macbook',
    projectPath: '/Users/kayamoran/Desktop/OPenClawInterface',
    status: 'active',
    startedAt: Date.now() - 600000,
    lastActivityAt: Date.now() - 15000,
    toolCalls: 24,
    filesModified: 7,
    tokenCount: 48200,
  },
  {
    id: 'csess-2',
    machineId: 'machine-2',
    machineName: 'staging-server',
    projectPath: '/opt/apps/api-service',
    status: 'active',
    startedAt: Date.now() - 180000,
    lastActivityAt: Date.now() - 8000,
    toolCalls: 12,
    filesModified: 3,
    tokenCount: 22100,
  },
];

export const mockCodeEvents: CodeEvent[] = [
  {
    id: 'cevt-1',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'session_start',
    timestamp: Date.now() - 600000,
    message: 'Session started in /Users/kayamoran/Desktop/OPenClawInterface',
  },
  {
    id: 'cevt-2',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'tool_use',
    timestamp: Date.now() - 580000,
    toolName: 'Read',
    filePath: 'src/app/layout.tsx',
    message: 'Read file src/app/layout.tsx',
  },
  {
    id: 'cevt-3',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'tool_use',
    timestamp: Date.now() - 540000,
    toolName: 'Glob',
    message: 'Searched for **/*.ts pattern',
    data: { pattern: '**/*.ts', matchCount: 42 },
  },
  {
    id: 'cevt-4',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'file_edit',
    timestamp: Date.now() - 480000,
    toolName: 'Edit',
    filePath: 'src/types/code-monitor.ts',
    message: 'Created new types file for code monitor feature',
  },
  {
    id: 'cevt-5',
    machineId: 'machine-2',
    sessionId: 'csess-2',
    type: 'session_start',
    timestamp: Date.now() - 180000,
    message: 'Session started in /opt/apps/api-service',
  },
  {
    id: 'cevt-6',
    machineId: 'machine-2',
    sessionId: 'csess-2',
    type: 'tool_use',
    timestamp: Date.now() - 160000,
    toolName: 'Bash',
    message: 'Ran npm test -- --coverage',
    data: { command: 'npm test -- --coverage', exitCode: 0 },
  },
  {
    id: 'cevt-7',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'file_edit',
    timestamp: Date.now() - 420000,
    toolName: 'Write',
    filePath: 'src/lib/code-monitor/state.ts',
    message: 'Created server-side state singleton',
  },
  {
    id: 'cevt-8',
    machineId: 'machine-2',
    sessionId: 'csess-2',
    type: 'tool_use',
    timestamp: Date.now() - 120000,
    toolName: 'Grep',
    message: 'Searched for "export function" in src/',
    data: { pattern: 'export function', matchCount: 18 },
  },
  {
    id: 'cevt-9',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'error',
    timestamp: Date.now() - 360000,
    message: 'TypeScript compilation error: Property "status" does not exist on type "Machine"',
    data: { file: 'src/lib/code-monitor/state.ts', line: 42 },
  },
  {
    id: 'cevt-10',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'file_edit',
    timestamp: Date.now() - 300000,
    toolName: 'Edit',
    filePath: 'src/lib/code-monitor/state.ts',
    message: 'Fixed type error in MonitorState class',
  },
  {
    id: 'cevt-11',
    machineId: 'machine-2',
    sessionId: 'csess-2',
    type: 'file_edit',
    timestamp: Date.now() - 90000,
    toolName: 'Edit',
    filePath: 'src/routes/health.ts',
    message: 'Updated health check endpoint with new fields',
  },
  {
    id: 'cevt-12',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'tool_use',
    timestamp: Date.now() - 240000,
    toolName: 'Bash',
    message: 'Ran npm run build to verify compilation',
    data: { command: 'npm run build', exitCode: 0 },
  },
  {
    id: 'cevt-13',
    machineId: 'machine-3',
    type: 'session_start',
    timestamp: Date.now() - 130000,
    message: 'CI session started for PR #247',
  },
  {
    id: 'cevt-14',
    machineId: 'machine-3',
    type: 'error',
    timestamp: Date.now() - 125000,
    message: 'Connection lost to dashboard during CI run',
    data: { reason: 'ECONNREFUSED', retries: 3 },
  },
  {
    id: 'cevt-15',
    machineId: 'machine-3',
    type: 'session_end',
    timestamp: Date.now() - 120000,
    message: 'Session terminated due to connection failure',
  },
  {
    id: 'cevt-16',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'message',
    timestamp: Date.now() - 60000,
    message: 'Agent completed implementation of code monitor types and state management',
  },
  {
    id: 'cevt-17',
    machineId: 'machine-2',
    sessionId: 'csess-2',
    type: 'tool_use',
    timestamp: Date.now() - 30000,
    toolName: 'Read',
    filePath: 'package.json',
    message: 'Read package.json to check dependencies',
  },
  {
    id: 'cevt-18',
    machineId: 'machine-1',
    sessionId: 'csess-1',
    type: 'tool_use',
    timestamp: Date.now() - 15000,
    toolName: 'Bash',
    message: 'Ran git status to check working tree',
    data: { command: 'git status', exitCode: 0 },
  },
];

export const mockWatchedProjects: WatchedProject[] = [
  {
    name: 'my-api',
    path: '/Users/kayamoran/Desktop/my-api',
    encodedDir: '-Users-kayamoran-Desktop-my-api',
    activeSessions: 1,
    totalSessions: 3,
    lastActivity: Date.now() - 15000,
  },
  {
    name: 'frontend-app',
    path: '/Users/kayamoran/Desktop/frontend-app',
    encodedDir: '-Users-kayamoran-Desktop-frontend-app',
    activeSessions: 0,
    totalSessions: 2,
    lastActivity: Date.now() - 300000,
  },
  {
    name: 'data-pipeline',
    path: '/Users/kayamoran/Desktop/data-pipeline',
    encodedDir: '-Users-kayamoran-Desktop-data-pipeline',
    activeSessions: 1,
    totalSessions: 1,
    lastActivity: Date.now() - 8000,
  },
];

export const mockCodeCommands: CodeCommand[] = [
  {
    id: 'ccmd-1',
    machineId: 'machine-1',
    instruction: 'Review the current implementation of the dashboard layout and suggest improvements for accessibility',
    status: 'pending',
    createdAt: Date.now() - 45000,
  },
  {
    id: 'ccmd-2',
    machineId: 'machine-2',
    instruction: 'Run the full test suite and report any failing tests with their error messages',
    status: 'pending',
    createdAt: Date.now() - 20000,
  },
];
