import type { AlertRule, AlertEvent } from '@/types/alert';

export const mockAlertRules: AlertRule[] = [
  {
    id: 'rule-1',
    name: 'High Error Rate',
    metric: 'error_rate',
    operator: '>',
    threshold: 5,
    severity: 'warning',
    actions: { notification: true, webhook: false },
    enabled: true,
    cooldownMinutes: 5,
  },
  {
    id: 'rule-2',
    name: 'Cost Spike',
    metric: 'cost',
    operator: '>',
    threshold: 10,
    severity: 'critical',
    actions: { notification: true, webhook: true },
    webhookUrl: 'https://hooks.example.com/alerts',
    enabled: true,
    cooldownMinutes: 15,
  },
];

export const mockAlertEvents: AlertEvent[] = [
  {
    id: 'alert-1',
    ruleId: 'rule-1',
    ruleName: 'High Error Rate',
    currentValue: 7.2,
    threshold: 5,
    message: 'Error rate reached 7.2%, exceeding threshold of 5%',
    severity: 'warning',
    acknowledged: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'alert-2',
    ruleId: 'rule-2',
    ruleName: 'Cost Spike',
    currentValue: 14.5,
    threshold: 10,
    message: 'Cost reached $14.50, exceeding threshold of $10.00',
    severity: 'critical',
    acknowledged: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'alert-3',
    ruleId: 'rule-1',
    ruleName: 'High Error Rate',
    currentValue: 6.1,
    threshold: 5,
    message: 'Error rate reached 6.1%, exceeding threshold of 5%',
    severity: 'warning',
    acknowledged: true,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'alert-4',
    ruleId: 'rule-2',
    ruleName: 'Cost Spike',
    currentValue: 12.3,
    threshold: 10,
    message: 'Cost reached $12.30, exceeding threshold of $10.00',
    severity: 'critical',
    acknowledged: true,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
];
