import { readFileSync, writeFileSync, mkdirSync, existsSync, chmodSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

interface HooksConfig {
  hooks?: {
    PostToolUse?: HookEntry[];
    Notification?: HookEntry[];
    [key: string]: HookEntry[] | undefined;
  };
}

interface HookEntry {
  type: 'command';
  command: string;
}

export function generateHookScript(
  agentDir: string,
  dashboardUrl: string,
  machineId: string,
  token: string
): string {
  const scriptPath = join(agentDir, 'hook-reporter.sh');

  const scriptContent = `#!/usr/bin/env bash
# Auto-generated by claude-monitor-agent
# Reports Claude Code hook events to the OpenClaw dashboard

DASHBOARD_URL="${dashboardUrl}"
MACHINE_ID="${machineId}"
TOKEN="${token}"

# Read hook event JSON from stdin
INPUT=$(cat)

# Wrap with machineId and POST to dashboard
PAYLOAD=$(cat <<INNEREOF
{
  "machineId": "$MACHINE_ID",
  "hookData": $INPUT
}
INNEREOF
)

curl -s -X POST \\
  -H "Content-Type: application/json" \\
  -H "X-Monitor-Token: $TOKEN" \\
  -d "$PAYLOAD" \\
  "$DASHBOARD_URL/api/code-monitor/events" >/dev/null 2>&1 &
`;

  writeFileSync(scriptPath, scriptContent, 'utf-8');
  chmodSync(scriptPath, 0o755);
  console.log(`[hooks] Generated hook reporter script at ${scriptPath}`);
  return scriptPath;
}

export function setupHooks(
  dashboardUrl: string,
  machineId: string,
  token: string,
  agentDir: string
): void {
  const scriptPath = generateHookScript(agentDir, dashboardUrl, machineId, token);

  const claudeDir = join(homedir(), '.claude');
  const hooksPath = join(claudeDir, 'hooks.json');

  // Ensure .claude directory exists
  if (!existsSync(claudeDir)) {
    mkdirSync(claudeDir, { recursive: true });
  }

  // Load existing hooks config or create new one
  let config: HooksConfig = {};
  if (existsSync(hooksPath)) {
    try {
      const existing = readFileSync(hooksPath, 'utf-8');
      config = JSON.parse(existing) as HooksConfig;
      console.log('[hooks] Found existing hooks.json, merging configuration');
    } catch {
      console.warn('[hooks] Could not parse existing hooks.json, creating new one');
    }
  }

  if (!config.hooks) {
    config.hooks = {};
  }

  const hookCommand = scriptPath;
  const monitorHook: HookEntry = {
    type: 'command',
    command: hookCommand,
  };

  // Add PostToolUse hook
  if (!config.hooks.PostToolUse) {
    config.hooks.PostToolUse = [];
  }
  // Remove any existing monitor hooks before adding
  config.hooks.PostToolUse = config.hooks.PostToolUse.filter(
    (h) => !h.command.includes('hook-reporter.sh')
  );
  config.hooks.PostToolUse.push(monitorHook);

  // Add Notification hook
  if (!config.hooks.Notification) {
    config.hooks.Notification = [];
  }
  config.hooks.Notification = config.hooks.Notification.filter(
    (h) => !h.command.includes('hook-reporter.sh')
  );
  config.hooks.Notification.push(monitorHook);

  writeFileSync(hooksPath, JSON.stringify(config, null, 2), 'utf-8');
  console.log(`[hooks] Updated hooks.json at ${hooksPath}`);
  console.log('[hooks] Configured PostToolUse and Notification hooks');
}
